---
name: Quality Assurance
on:
    push:
        branches: ['main']
    pull_request: ~

jobs:
    tests:
        name: Tests on ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.4', '8.5']
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer:v2
            - run: composer install --no-progress
            - run: vendor/bin/phpunit
